version: "3"
services:
  php_laravel:
    build: ./php
    image: php:latest
    container_name: php_laravel
    hostname: "php"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - mysql_laravel

  mysql_laravel:
    image: mariadb:10.2
    container_name: mysql_laravel
    restart: unless-stopped
    tty: true
    ports:
      - "33306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    read_only: false

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_laravel
    restart: unless-stopped
    ports:
      - "8081:80" # Akses via http://localhost:8081
    environment:
      PMA_HOST: mysql_laravel # Nama service MariaDB di atas
      PMA_USER: root
      PMA_PASSWORD: 123
      UPLOAD_LIMIT: 64M # Batas maksimal import SQL
    depends_on:
      - mysql_laravel

  nginx_laravel:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_laravel
    hostname: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_laravel
